export { default as close } from "./close.svg";
export { default as emailIcon } from "./email-icon.svg";
export { default as githubIcon } from "./github-icon.svg";
export { default as leftArrow } from "./left-arrow.svg";
export { default as linkedinIcon } from "./linkedin-icon.svg";
export { default as menu } from "./menu.svg";
export { default as rightArrow } from "./right-arrow.svg";
export { default as swiftLearner } from "./swift-learner.svg";
export { default as vaultMeThumbsUp } from "./vault-me-thumbs-up.svg";
